export const CHANGE_SEARCH_FIELD = "CHANGE_SEARCH_FIELD";
export const REQUEST_MEGAS_PENDING = "REQUEST_MEGAS_PENDING";
export const REQUEST_MEGAS_SUCCESS = "REQUEST_MEGAS_SUCCESS";
export const REQUEST_MEGAS_FAILED = "REQUEST_MEGAS_FAILED";